services:

  postgres:
    image: postgres:17
    container_name: shopsphere-postgres
    environment:
      POSTGRES_DB: shopsphere
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: shopsphere-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shopsphere.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5433:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
